# Github Pages Overrides (ensure local serve mimics live)
lsi: false
source: .
highlighter: pygments

# Github Pages Atom feed generation
gems:
  - jekyll-feed

# Personal Choices
permalink: /blog/:categories/:title
relative_permalinks: false
paginate: 10
paginate_path: "/blog/page:num/"
repository: https://github.com/brobotic-studios/brobotic-studios.github.io
timezone: America/New_York
encoding: utf-8
url: https://brobotic.com
name: Brobotic Studios
description: Welcome to the wonderful world of the Brobotic blog.
author:
  name: Brobotic Studios
  email: info@brobotic.com
  uri: https://brobotic.com

# Site-wide defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
  -
    scope:
      path: "blog"
      type: "pages"
    values:
      layout: "blog"
